Repository atlp-rwanda/code-ninjas-be, pull requests merged in 2022-04, with the labels that each got.

#32 #181414758 feature(login):create user login functionality
  .DS_Store
  .env.example
  .eslintrc.json
  package.json
  public/swagger/auth.doc.js
  public/swagger/index.js
  public/swagger/response.js
  public/swagger/user.doc.js
  src/.DS_Store
  src/app.js
  src/controllers/auth.js
  src/controllers/user.js
  src/database/.DS_Store
  src/database/config/config.js
  src/database/config/database.js
  src/database/migrations/20220309061357-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20220302143415-demo-user.js
  src/helpers/encryption.js
  src/helpers/validator.js
  src/middlewares/logger.js
  src/middlewares/validator.js
  src/routes/auth.js
  src/routes/index.js
  src/services/user.js
  src/swagger/index.js
  src/utils/errorResponse.js
  src/utils/successResponse.js
  test/auth.test.js
  test/mocks/index.js
  test/usertest.spec.js
  yarn.lock
Labels: enhancement, Ready for TTL Review

#36 #181414754 ch(Docker-Setup): Setup docker
  .dockerignore
  Dockerfile
Labels: enhancement, setup, Ready For Review

#25 #181414759 Ft(login with social media) added google and Facebook login functionality
  .env.example
  .github/workflows/Node.js.yml
  .vscode/settings.json
  package.json
  src/app.js
  src/controllers/FacebookSocialController.js
  src/controllers/GoogleSocialController.js
  src/database/migrations/20220331083931-modify_users_add_new_fields.js
  src/database/models/user.js
  src/database/seeders/20220302143415-demo-user.js
  src/helpers/CheckUser.js
  src/middlewares/auth.js
  src/routes/auth.js
  src/routes/index.js
  src/routes/user.js
  src/services/facebookPassport.js
  src/services/googlePassport.js
  src/swagger/index.js
  test/mocks/index.js
  test/socialLogin.spec.js
  views/login.ejs
  yarn.lock
Labels: enhancement, Ready for TTL Review

#38 #181414758 feature(login):create user login functionality
  .DS_Store
  .env.example
  package.json
  src/.DS_Store
  src/app.js
  src/controllers/auth.js
  src/database/.DS_Store
  src/database/config/config.js
  src/database/config/database.js
  src/database/migrations/20220309061357-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20220302143415-demo-user.js
  src/helpers/encryption.js
  src/helpers/validator.js
  src/middlewares/logger.js
  src/middlewares/validator.js
  src/routes/auth.js
  src/routes/index.js
  src/services/user.js
  src/swagger/index.js
  src/swagger/response.js
  src/utils/errorResponse.js
  src/utils/successResponse.js
  test/auth.test.js
  test/mocks/index.js
  test/usertest.spec.js
  yarn.lock
Labels: documentation, enhancement, Changes requested

#40 #181414760 feature(logout):create user logout functionality
  .env.example
  .github/workflows/Node.js.yml
  package.json
  src/controllers/FacebookSocialController.js
  src/controllers/GoogleSocialController.js
  src/controllers/auth.js
  src/database/config/database.js
  src/database/config/redis.config.js
  src/helpers/encryption.js
  src/middlewares/token.js
  src/routes/auth.js
  src/services/token.js
  src/swagger/index.js
  test/auth.test.js
  test/mocks/index.js
  test/usertest.spec.js
  yarn.lock
Labels: enhancement, Ready For Review

#35 #181414756 (feature): Send a verification email on registration
  .env.example
  .github/workflows/Node.js.yml
  .nycrc.json
  package.json
  src/app.js
  src/controllers/FacebookSocialController.js
  src/controllers/GoogleSocialController.js
  src/controllers/auth.js
  src/controllers/user.js
  src/database/config/config.js
  src/database/config/database.js
  src/database/config/redis.config.js
  src/database/redis.js
  src/helpers/CheckUser.js
  src/helpers/email/config.js
  src/helpers/email/index.js
  src/helpers/email/templates.js
  src/helpers/index.js
  src/helpers/token.js
  src/helpers/validator.js
  src/middlewares/EmailValidation.js
  src/middlewares/auth.js
  src/middlewares/index.js
  src/middlewares/login.js
  src/middlewares/token.js
  src/middlewares/validator.js
  src/routes/auth.js
  src/routes/index.js
  src/routes/user.js
  src/services/CheckUser.js
  src/services/TokenService.js
  src/services/UserServices.js
  src/services/token.js
  src/services/user.js
  src/services/user.service.js
  src/swagger/auth.doc.js
  src/swagger/components/index.js
  src/swagger/components/schemas/index.js
  src/swagger/components/schemas/login.js
  src/swagger/components/schemas/security.js
  src/swagger/components/schemas/user.js
  src/swagger/index.js
  src/swagger/user.doc.js
  src/swagger/utils/responses.js
  src/utils/errorResponse.js
  src/utils/successResponse.js
  src/validations/EmailValidation.js
  src/validations/UserValidation.js
  src/validations/index.js
  src/validations/loginValidation.js
  test/auth.test.js
  test/fixtures/db.js
  test/mocks/index.js
  test/usertest.spec.js
  test/verifyEmail.test.js
  yarn.lock
Labels: enhancement, Changes requested

#42 #181414762 (feature): Send a reset password email
  src/app.js
  src/controllers/auth.js
  src/controllers/email.js
  src/controllers/user.js
  src/helpers/email/templates.js
  src/middlewares/auth.js
  src/middlewares/login.js
  src/routes/user.js
  src/swagger/components/schemas/index.js
  src/swagger/components/schemas/newPassword.js
  src/swagger/components/schemas/security.js
  src/swagger/user.doc.js
  src/validations/EmailValidation.js
  src/validations/index.js
  src/validations/newPasswordValidation.js
  test/fixtures/db.js
  test/resetPassword.spec.js
  test/verifyEmail.test.js
Labels: enhancement, Ready For Review

#44 fx(reset-password): making tests pass
  src/controllers/FacebookSocialController.js
  src/controllers/GoogleSocialController.js
  src/controllers/auth.js
  src/controllers/email.js
  src/controllers/user.js
  src/helpers/email/index.js
  src/helpers/encryption.js
  src/helpers/token.js
  src/middlewares/auth.js
  src/middlewares/token.js
  src/routes/auth.js
  src/routes/user.js
  src/services/token.js
  src/swagger/auth.doc.js
  src/swagger/components/index.js
  src/swagger/components/parameters/email.js
  src/swagger/components/parameters/id.js
  src/swagger/components/parameters/index.js
  src/swagger/components/parameters/token.js
  src/swagger/user.doc.js
  src/utils/errorResponse.js
  test/auth.test.js
  test/resetPassword.spec.js
  test/verifyEmail.test.js
Labels: Ready For Review

#33 Ft user role 181414757
  .env.example
  .github/workflows/Node.js.yml
  package.json
  src/config/config.js
  src/config/init.js
  src/controllers/auth.js
  src/controllers/user.js
  src/database/migrations/20220405214034-create-role.js
  src/database/migrations/20220405214715-modify_users_add_new_fields.js
  src/database/migrations/20220417205059-update_roles_datatype.js
  src/database/models/role.js
  src/database/models/user.js
  src/database/seeders/20220302143415-demo-user.js
  src/database/seeders/20220411084040-Role.js
  src/helpers/CheckUser.js
  src/helpers/roles.js
  src/helpers/token.js
  src/middlewares/auth.js
  src/middlewares/superadminAuth.js
  src/routes/auth.js
  src/routes/index.js
  src/routes/roles.js
  src/routes/user.js
  src/services/RolesServices.js
  src/swagger/index.js
  src/swagger/roles.doc.js
  src/validations/UserValidation.js
  test/auth.test.js
  test/mocks/index.js
  test/roles.test.js
  test/usertest.spec.js
  yarn.lock
Labels: Ready For Review
