Repository atlp-rwanda/code-ninjas-be, pull requests merged in 2022-03, with the labels that each got.

#12 #181414702 chore(Configure Eslint): Setup project files to use Eslint with AirBnB
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierrc.json
  package.json
  src/app.js
  src/index.js
  yarn.lock
Labels: enhancement, good first issue, setup, bn node/express backend, Ready For Review

#13 #181414703 chore(Integrate HoundCI): Integrate HoundCI with badge attached to re…
  .eslintrc.js
  .hound.yml
  .husky/_/.gitignore
  .prettierrc.json
  README.md
  package.json
  src/app.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/config/database.js
  src/index.js
  src/routes/userRoute.js
  yarn.lock
Labels: enhancement, good first issue, setup, bn node/express backend, Ready For Review

#20 #181414752 chore(setup-documentation): Setup API documentation using swagger
  .env.example
  .eslintrc.js
  .eslintrc.json
  .hound.yml
  .husky/pre-commit
  package.json
  src/app.js
  src/controllers/user.js
  src/database/config/config.js
  src/database/config/database.js
  src/database/migrations/20220302143333-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20220302143415-demo-user.js
  src/index.js
  src/routes/index.js
  src/routes/user.js
  src/routes/userRoute.js
  src/swagger/index.js
  src/swagger/response.js
  yarn.lock
Labels: documentation, enhancement, good first issue, setup, Ready For Review, Ready for TTL Review

#31 #181414705 (chore) CI testing with Github actions
  .babelrc
  .github/workflows/Node.js.yml
  .husky/pre-commit
  .prettierrc.json
  README.md
  package.json
  src/database/config/config.js
  src/database/config/database.js
  src/database/migrations/20220302143333-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20220302143415-demo-user.js
  src/index.js
  src/routes/index.js
  src/routes/user.js
  test/usertest.spec.js
  yarn.lock
Labels: good first issue, setup, WIP, Ready For Review, Changes requested
